name: Android CI

on:
  push:
    branches: 
      main
  pull_request:
    branches: 
      - '*'

jobs:
  bidder_token_generation_time:
    name: Bidder Token Generation Time
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permssion for gradlew
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: Build report
          path: app/build/reports
        if: always()
